### ISSUE TITLE
chown: changing ownership of ‘/var/jenkins_home’: Operation not permitted

### ISSUE THREAD

**Issue by KeithTt** [denverdino/docker-jenkins#3]
I build a image, and run it with k8s, i use nfs for the volume, in this case the shell script `https://github.com/AliyunContainerService/docker-jenkins/blob/master/jenkins/entrypoint.sh` is not work.

the error details is the tiltle.
`chown: changing ownership of ‘/var/jenkins_home’: Operation not permitted`

OS ver: centos7.2
k8s ver: 1.5

Here is my yaml file:
```
---
apiVersion: "v1"
kind: "Namespace"
metadata:
  name: "jenkins"
  labels:
    name: "jenkins"
---
apiVersion: "v1"
kind: "ReplicationController"
metadata:
  name: "jenkins"
  namespace: "jenkins"
  labels:
    name: "jenkins"
spec:
  replicas: 1
  template:
    metadata:
      name: "jenkins"
      namespace: "jenkins"
      labels:
        name: "jenkins"
    spec:
      containers:
      - name: "jenkins"
        image: "172.60.0.107/jenkins/jenkins:v1"
        ports:
        - containerPort: 8080
        - containerPort: 50000
        volumeMounts:
        - name: "jenkins"
          mountPath: "/var/jenkins_home"
      volumes:
      - name: "jenkins"
        hostPath:
          path: "/opt/jenkins"
---
apiVersion: "v1"
kind: "ReplicationController"
metadata:
  name: "jenkins"
  namespace: "jenkins"
  labels:
    name: "jenkins"
spec:
  replicas: 1
  template:
    metadata:
      name: "jenkins"
      namespace: "jenkins"
      labels:
        name: "jenkins"
    spec:
      containers:
      - name: "jenkins"
        image: "172.60.0.107/jenkins/jenkins:v1"
        ports:
        - containerPort: 8080
        - containerPort: 50000
        volumeMounts:
        - name: "jenkins"
          mountPath: "/var/jenkins_home"
      volumes:
      - name: "jenkins"
        hostPath:
          path: "/opt/jenkins"
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "jenkins"
  namespace: "jenkins"
spec:
  type: "NodePort"
  selector:
    name: "jenkins"
  ports:
    - name: "http"
      port: 80
      targetPort: 8080
      protocol: "TCP"
    - name: "slave"
      port: 50000
      protocol: "TCP"
```
